# Generated by Django 3.0.2 on 2020-02-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200204_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='vehicle',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
