# Generated by Django 3.0.2 on 2020-02-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200204_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
