# Generated by Django 3.0.2 on 2020-02-05 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200204_1217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='driver',
            new_name='driver_id',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='isComplete',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
