# Generated by Django 3.0.2 on 2020-02-05 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200204_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='vehicle',
            field=models.CharField(blank=True, default='car', max_length=50),
        ),
    ]
